import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/network/api_client.dart';
import '../../../core/network/api_config.dart';
import '../../../core/network/api_result.dart';

enum ExerciseCategory { family, colors, fruits, dailyLife }

class ExerciseTopic {
  const ExerciseTopic({required this.id, required this.title, required this.category});

  final String id;
  final String title;
  final ExerciseCategory category;

  factory ExerciseTopic.fromJson(Map<String, dynamic> json) => ExerciseTopic(
        id: json['id'].toString(),
        title: json['title'] as String,
        category: ExerciseCategory.values.firstWhere(
          (c) => c.name == json['category'],
          orElse: () => ExerciseCategory.dailyLife,
        ),
      );
}

/// The exercise set is generated by the AI engine (FR-35). This app only
/// consumes it and reports results back:
///   GET  /api/exercises/today            -> topics + difficulty (AI owned)
///   POST /api/exercises/:id/results      -> answers, duration
abstract class ExerciseRepository {
  Future<ApiResult<List<ExerciseTopic>>> todayTopics();
}

class ApiExerciseRepository implements ExerciseRepository {
  ApiExerciseRepository(this._client);
  final ApiClient _client;

  @override
  Future<ApiResult<List<ExerciseTopic>>> todayTopics() => _client.get(
        '/exercises/today',
        (json) => (json as List)
            .map((e) => ExerciseTopic.fromJson(Map<String, dynamic>.from(e as Map)))
            .toList(),
      );
}

class MockExerciseRepository implements ExerciseRepository {
  @override
  Future<ApiResult<List<ExerciseTopic>>> todayTopics() async {
    await Future<void>.delayed(const Duration(milliseconds: 350));
    return const Success([
      ExerciseTopic(id: '1', title: 'التعرف على أفراد العائلة', category: ExerciseCategory.family),
      ExerciseTopic(id: '2', title: 'التعرف على الألوان', category: ExerciseCategory.colors),
      ExerciseTopic(id: '3', title: 'التعرف على الفواكه', category: ExerciseCategory.fruits),
      ExerciseTopic(id: '4', title: 'أسئلة الحياة اليومية', category: ExerciseCategory.dailyLife),
    ]);
  }
}

final exerciseRepositoryProvider = Provider<ExerciseRepository>((ref) => ApiConfig.useMockData
    ? MockExerciseRepository()
    : ApiExerciseRepository(ref.watch(apiClientProvider)));
